title: My first blog on github pages
author: Fafemi Adeola
email: adeola5678@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first github pages blog.

# social links
twitter_username: kojusola # DO NOT include the @ character, or else the build will fail!
github_username:  kojusola # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
